sudo: require

language: java

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    set -e;
    export REPO=$DOCKER_USERNAME/$DOCKER_IMAGE_NAME;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t $REPO:$TRAVIS_COMMIT .;
    docker tag $REPO:$TRAVIS_COMMIT $REPO:latest;
    docker push $REPO:latest;
    fi

branches:
  only:
  - master

notifications:
  slack:
    secure: L7zAkyc0+j0sHBYGhwF3VKFMkcDD1qg3DTzz0NuHyFh8MGpcvDtqPLPM4mDZ2ACKcsXBP7iPH+TXqSwVzmy71NDuTv+j/Hmb2lVStm3CXDJH3i58pY6Cgoew1nrKN7r7+Atj4nEeU0U/ycvJqJ4M+X1LfBW/mlOY8jlmWL+yBOTdwA2iknlzKbdyk+6AKdl2eZCOEeqroddUY1GfwBptOxy9/2Kf5Gto9KRrZFzDhOuqUXFTfNM3uxHB+NYBPfAorQM1Jtoz7Oq7Kyxm5AbLXC0vvHJVAzZjS1vT4ns8G4o1B++xSxHv/AcFv8/G+fb94unkrx+hiW3DVMrpHW0izvNGxOJDjkR5libbT8BcJ74KwiC7ay5cBBPTgzLTEiNrN6wC1BSSEAoUYUhVtcWYqrvKWoODOU2iNiqkqUuBOkg+wEZQ+0GQsy73MG3Sa9btSTYzbq2QRPrHzev2OtSqaW/fNBstIsbjJjFPb6KbrEoKJ9Z9H2ZWWQ+tkFUxbDr1blJpSUFFnxmfTQZCD9vfqdWHaClUg7yVMAXG6E7q2XwZY3Bi8EQ1AWv8y5NXzLAzGKgGyzTc4o0uyBHIXGRpZFE+/ZfAC8KleqBz9zbFliI3xl/mK0ExWbDHclF6FJnjsOOQziXg6O9toFBdae0sCaH3+wscuRgGCckxl1wjYxU=
