sudo: require

language: java

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    set -e;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    export BACKEND_REPO=$DOCKER_ORGANIZATION/resume-builder-bot;
    docker build -t $BACKEND_REPO:$TRAVIS_COMMIT .;
    docker tag $BACKEND_REPO:$TRAVIS_COMMIT $BACKEND_REPO:latest;

    export POSTGRES_REPO=$DOCKER_ORGANIZATION/resume-builder-bot-postgres;
    docker build -f Dockerfile.postgres -t $POSTGRES_REPO:$TRAVIS_COMMIT .;
    docker tag $POSTGRES_REPO:$TRAVIS_COMMIT $POSTGRES_REPO:latest;

    docker push $BACKEND_REPO:latest;
    docker push $POSTGRES_REPO:latest;
    fi

branches:
  only:
  - master

notifications:
  slack:
    rooms:
      - hh-school:57VpRcwmEQfuhxnzImuD4JLX
    on_success: change
