sudo: require

services:
  - docker

script:
  - echo "run tests here"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export REPO=$DOCKER_USERNAME/$DOCKER_IMAGE_NAME;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t $REPO:$TRAVIS_COMMIT .;
    docker tag $REPO:$TRAVIS_COMMIT $REPO:latest;
    docker push $REPO:latest;
    fi
