version: "3"

services:
  backend:
    container_name: resume_builder_bot_backend
    image: bkhasanov/resume-builder-bot
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: always

  postgres:
    container_name: resume_builder_bot_postgres
    image: bkhasanov/resume-builder-bot-postgres
    env_file: .env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
