version: "3"

services:
  backend:
    build: .  
    container_name: resume_builder_bot_backend
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: always

  postgres:
    container_name: resume_builder_bot_postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
