package ru.hh.resumebuilderbot.texts.storage;

public enum TextId {
    ALREADY_STARTED, UNKNOWN, OOPS_TRY_RESTART, HELLO, CLEARED, FINISHED, EMPTY,
    INVALID_ANSWER, CANT_SKIP, NO_FACULTIES_FOUND, NO_FACULTIES_FOUND_DESCRIPTION,
    CONTINUE_INPUT, NOTHING_SELECTED, NEED_MORE_ONE_SYMBOL, CHECK_INPUT_DATA
}
