package ru.hh.resumebuilderbot.question;

public enum ReplyKeyboardEnum {
    NO_KEYBOARD_NEEDED,
    VARIANTS_OF_ANSWER,
    PHONE_NUMBER,
    DATE_WITH_DAY,
    DATE_WITHOUT_DAY,
    YEAR,
    SUGGEST,
    UPDATE_YEAR_WITH_DAY,
    UPDATE_YEAR_WITHOUT_DAY,
    UPDATE_YEAR_WITHOUT_MONTH,
    UPDATE_MONTH_WITHOUT_DAY,
    UPDATE_MONTH_WITH_DAY,
    UPDATE_DAY
}
